// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Eng91FinalProject.BDD.TrainerProfile
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("TrainerProfilePage")]
    public partial class TrainerProfilePageFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "TrainerProfile.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "BDD/TrainerProfile", "TrainerProfilePage", "\tLanding page of trainer profile", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Navigate to trainer profile page")]
        [NUnit.Framework.CategoryAttribute("Trainer_page")]
        public virtual void NavigateToTrainerProfilePage()
        {
            string[] tagsOfScenario = new string[] {
                    "Trainer_page"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Navigate to trainer profile page", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 5
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
<<<<<<< HEAD
                TechTalk.SpecFlow.Table table64 = new TechTalk.SpecFlow.Table(new string[] {
=======
                TechTalk.SpecFlow.Table table62 = new TechTalk.SpecFlow.Table(new string[] {
>>>>>>> a5a24b7e942299fa6c2f38e14da2c611f0625300
                            "Email",
                            "Password"});
                table64.AddRow(new string[] {
                            "jsmith@spartaglobal.com",
                            "Password123!"});
#line 6
<<<<<<< HEAD
testRunner.Given("I am logged in", ((string)(null)), table64, "Given ");
=======
testRunner.Given("I am logged in", ((string)(null)), table62, "Given ");
>>>>>>> a5a24b7e942299fa6c2f38e14da2c611f0625300
#line hidden
#line 9
testRunner.When("I click my name to view my Profile Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 10
testRunner.Then("I am taken to my Profile Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Edit and Save changes")]
        [NUnit.Framework.CategoryAttribute("Trainer_page")]
        public virtual void EditAndSaveChanges()
        {
            string[] tagsOfScenario = new string[] {
                    "Trainer_page"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Edit and Save changes", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 13
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
<<<<<<< HEAD
                TechTalk.SpecFlow.Table table65 = new TechTalk.SpecFlow.Table(new string[] {
=======
                TechTalk.SpecFlow.Table table63 = new TechTalk.SpecFlow.Table(new string[] {
>>>>>>> a5a24b7e942299fa6c2f38e14da2c611f0625300
                            "Email",
                            "Password"});
                table65.AddRow(new string[] {
                            "jsmith@spartaglobal.com",
                            "Password123!"});
#line 14
<<<<<<< HEAD
testRunner.Given("I am logged in", ((string)(null)), table65, "Given ");
=======
testRunner.Given("I am logged in", ((string)(null)), table63, "Given ");

>>>>>>> a5a24b7e942299fa6c2f38e14da2c611f0625300
#line hidden
#line 17
testRunner.When("I click my name to view my Profile Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 18
testRunner.And("I click EDIT", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
<<<<<<< HEAD
                TechTalk.SpecFlow.Table table66 = new TechTalk.SpecFlow.Table(new string[] {
=======
                TechTalk.SpecFlow.Table table64 = new TechTalk.SpecFlow.Table(new string[] {
>>>>>>> a5a24b7e942299fa6c2f38e14da2c611f0625300
                            "FirstName",
                            "LastName",
                            "Email",
                            "Location"});
<<<<<<< HEAD
                table66.AddRow(new string[] {
=======
                table64.AddRow(new string[] {
>>>>>>> a5a24b7e942299fa6c2f38e14da2c611f0625300
                            "Test",
                            "Name",
                            "test@snailmail.com",
                            "North Pole"});
#line 19
<<<<<<< HEAD
testRunner.And("I update my details with the following information", ((string)(null)), table66, "And ");
=======
testRunner.And("I update my details with the following information", ((string)(null)), table64, "And ");
>>>>>>> a5a24b7e942299fa6c2f38e14da2c611f0625300
#line hidden
#line 22
testRunner.And("I click SAVE", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 23
testRunner.Then("my profile is updated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("change stream to C# dev")]
        [NUnit.Framework.CategoryAttribute("Trainer_page")]
        public virtual void ChangeStreamToCDev()
        {
            string[] tagsOfScenario = new string[] {
                    "Trainer_page"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("change stream to C# dev", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 26
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
<<<<<<< HEAD
                TechTalk.SpecFlow.Table table67 = new TechTalk.SpecFlow.Table(new string[] {
=======
                TechTalk.SpecFlow.Table table65 = new TechTalk.SpecFlow.Table(new string[] {
>>>>>>> a5a24b7e942299fa6c2f38e14da2c611f0625300
                            "Email",
                            "Password"});
                table67.AddRow(new string[] {
                            "jsmith@spartaglobal.com",
                            "Password123!"});
#line 27
<<<<<<< HEAD
testRunner.Given("I am logged in", ((string)(null)), table67, "Given ");
=======
testRunner.Given("I am logged in", ((string)(null)), table65, "Given ");
>>>>>>> a5a24b7e942299fa6c2f38e14da2c611f0625300
#line hidden
#line 30
testRunner.When("I click my name to view my Profile Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 31
testRunner.And("I click EDIT", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 32
testRunner.And("change my stream to \'C# Developer\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 33
testRunner.And("I click SAVE", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 34
testRunner.Then("my profile details for course stream should show \'C# Developer\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("change stream to C# SDET")]
        [NUnit.Framework.CategoryAttribute("Trainer_page")]
        public virtual void ChangeStreamToCSDET()
        {
            string[] tagsOfScenario = new string[] {
                    "Trainer_page"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("change stream to C# SDET", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 37
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
<<<<<<< HEAD
                TechTalk.SpecFlow.Table table68 = new TechTalk.SpecFlow.Table(new string[] {
=======
                TechTalk.SpecFlow.Table table66 = new TechTalk.SpecFlow.Table(new string[] {
>>>>>>> a5a24b7e942299fa6c2f38e14da2c611f0625300
                            "Email",
                            "Password"});
                table68.AddRow(new string[] {
                            "jsmith@spartaglobal.com",
                            "Password123!"});
#line 38
<<<<<<< HEAD
testRunner.Given("I am logged in", ((string)(null)), table68, "Given ");
=======
testRunner.Given("I am logged in", ((string)(null)), table66, "Given ");

>>>>>>> a5a24b7e942299fa6c2f38e14da2c611f0625300
#line hidden
#line 41
testRunner.When("I click my name to view my Profile Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 42
testRunner.And("I click EDIT", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 43
testRunner.And("change my stream to \'C# SDET\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 44
testRunner.And("I click SAVE", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 45
testRunner.Then("my profile details for course stream should show \'C# SDET\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("change stream to Java Developer")]
        [NUnit.Framework.CategoryAttribute("Trainer_page")]
        public virtual void ChangeStreamToJavaDeveloper()
        {
            string[] tagsOfScenario = new string[] {
                    "Trainer_page"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("change stream to Java Developer", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 48
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
<<<<<<< HEAD
                TechTalk.SpecFlow.Table table69 = new TechTalk.SpecFlow.Table(new string[] {
=======
                TechTalk.SpecFlow.Table table67 = new TechTalk.SpecFlow.Table(new string[] {
>>>>>>> a5a24b7e942299fa6c2f38e14da2c611f0625300
                            "Email",
                            "Password"});
                table69.AddRow(new string[] {
                            "jsmith@spartaglobal.com",
                            "Password123!"});
#line 49
<<<<<<< HEAD
testRunner.Given("I am logged in", ((string)(null)), table69, "Given ");
=======
testRunner.Given("I am logged in", ((string)(null)), table67, "Given ");

>>>>>>> a5a24b7e942299fa6c2f38e14da2c611f0625300
#line hidden
#line 52
testRunner.When("I click my name to view my Profile Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 53
testRunner.And("I click EDIT", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 54
testRunner.And("change my stream to \'Java Developer\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 55
testRunner.And("I click SAVE", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 56
testRunner.Then("my profile details for course stream should show \'Java Developer\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("change stream to DevOps")]
        [NUnit.Framework.CategoryAttribute("Trainer_page")]
        public virtual void ChangeStreamToDevOps()
        {
            string[] tagsOfScenario = new string[] {
                    "Trainer_page"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("change stream to DevOps", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 59
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
<<<<<<< HEAD
                TechTalk.SpecFlow.Table table70 = new TechTalk.SpecFlow.Table(new string[] {
=======
                TechTalk.SpecFlow.Table table68 = new TechTalk.SpecFlow.Table(new string[] {
>>>>>>> a5a24b7e942299fa6c2f38e14da2c611f0625300
                            "Email",
                            "Password"});
                table70.AddRow(new string[] {
                            "jsmith@spartaglobal.com",
                            "Password123!"});
#line 60
<<<<<<< HEAD
testRunner.Given("I am logged in", ((string)(null)), table70, "Given ");
=======
testRunner.Given("I am logged in", ((string)(null)), table68, "Given ");

>>>>>>> a5a24b7e942299fa6c2f38e14da2c611f0625300
#line hidden
#line 63
testRunner.When("I click my name to view my Profile Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 64
testRunner.And("I click EDIT", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 65
testRunner.And("change my stream to \'DevOps\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 66
testRunner.And("I click SAVE", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 67
testRunner.Then("my profile details for course stream should show \'DevOps\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("change stream to Business Analyst")]
        [NUnit.Framework.CategoryAttribute("Trainer_page")]
        public virtual void ChangeStreamToBusinessAnalyst()
        {
            string[] tagsOfScenario = new string[] {
                    "Trainer_page"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("change stream to Business Analyst", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 70
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
<<<<<<< HEAD
                TechTalk.SpecFlow.Table table71 = new TechTalk.SpecFlow.Table(new string[] {
=======
                TechTalk.SpecFlow.Table table69 = new TechTalk.SpecFlow.Table(new string[] {
>>>>>>> a5a24b7e942299fa6c2f38e14da2c611f0625300
                            "Email",
                            "Password"});
                table71.AddRow(new string[] {
                            "jsmith@spartaglobal.com",
                            "Password123!"});
#line 71
<<<<<<< HEAD
testRunner.Given("I am logged in", ((string)(null)), table71, "Given ");
=======
testRunner.Given("I am logged in", ((string)(null)), table69, "Given ");
>>>>>>> a5a24b7e942299fa6c2f38e14da2c611f0625300
#line hidden
#line 74
testRunner.When("I click my name to view my Profile Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 75
testRunner.And("I click EDIT", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 76
testRunner.And("change my stream to \'Business Analyst\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 77
testRunner.And("I click SAVE", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 78
testRunner.Then("my profile details for course stream should show \'Business Analyst\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
